# Generated by Django 5.0.4 on 2024-04-29 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0005_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='current_patient',
        ),
    ]
