# Generated by Django 5.0.4 on 2024-04-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0006_remove_bill_current_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugs',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
