# Generated by Django 5.0.4 on 2024-04-29 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0007_drugs_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drugs',
            name='quantity',
        ),
    ]
